version: "3.9"

services:
  service_caller:
    build: .
    container_name: service_caller
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /root/app/
    image: vicourtgcb/service_caller:latest
    ports:
      - "8000:8000"